// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITIWebApi.Models;

[Keyless]
[Table("stdHisto_audit")]
public partial class stdHisto_audit
{
    [StringLength(100)]
    [Unicode(false)]
    public string srtverName { get; set; }

    public DateOnly? _date { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string _note { get; set; }
}