  
@ITIWebApi_HostAddress=https://localhost:7003/api
  

###
GET {{ITIWebApi_HostAddress}}/students


###

GET {{ITIWebApi_HostAddress}}/students/0

###

DELETE {{ITIWebApi_HostAddress}}/students/1
##

GET {{ITIWebApi_HostAddress}}/Departments/20
##



